repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
      exclude: |
        (?x)^(
          .helmignore|
          templates/NOTES.txt|
          .*/templates/.*\.(yaml|ya?ml|json|tpl)
          )$
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs-built
        args:
          - --chart-search-root=./
          - --skip-version-footer
          - --template-files=./.templates.gotmpl
          - --template-files=README.md.gotmpl
